name: Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build with make
        run: make

      - name: Run the compiled binary with arguments
        run: ./keyhunt -m address -f tests/66.txt -r 363d541eb611abee0:39a11e93c3eb6300a -k 1024 -R -l compress -t 12 -q -s 10
        continue-on-error: true
